name: my_test_app_flavors
description: Networking app
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  # carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  get: ^4.6.5
  go_router: ^13.1.0
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image: ^4.2.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.0+3
  # url_launcher: ^6.1.14

dev_dependencies: 
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/  # Ensure you have this image in your project under the assets directory

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/raleway/Raleway-Medium.ttf
        - asset: fonts/raleway/Raleway-SemiBold.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
