// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzrWHov5N6RYagG2vn3UQzDm20AunVgE',
    appId: '1:733832077552:android:5538509c2ce74802bba235',
    messagingSenderId: '733832077552',
    projectId: 'conference-dev-5af5e',
    storageBucket: 'conference-dev-5af5e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMk1kyGcSvZUVHXvdBC5c1J_jXGS-4wSQ',
    appId: '1:733832077552:web:cc0aa31983116b6cbba235',
    messagingSenderId: '733832077552',
    projectId: 'conference-dev-5af5e',
    authDomain: 'conference-dev-5af5e.firebaseapp.com',
    storageBucket: 'conference-dev-5af5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgSR0oQ6UxjU7Z8qgE5e2lnynNOZvCcwc',
    appId: '1:733832077552:ios:83e4a1757b6242e3bba235',
    messagingSenderId: '733832077552',
    projectId: 'conference-dev-5af5e',
    storageBucket: 'conference-dev-5af5e.appspot.com',
    iosClientId:
        '733832077552-ilt97jqno2l6hdri88o5df5ia4hi5e2g.apps.googleusercontent.com',
    iosBundleId: 'com.codewithandrea.my-test-app-flavors',
  );
}
